#!/usr/bin/env bash
# Configure UFW to allow SSH, HTTP and HTTPS traffic only.

apt-get update -y
apt-get install -y ufw

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw --force enable
